### ISSUE TITLE
seal status/running checks should be debug messages

### ISSUE THREAD

**Issue by reverendj1** [lrstanley/vault-unseal#1]
Can these be changed to debug level messages, to avoid spamming the log with "everything is still working" messages every 15 seconds?

```
timestamp=2021-04-21T16:28:41.593169277-04:00 level=info message="seal status" addr=https://myserver:8200 environment= version=v0.0.6
timestamp=2021-04-21T16:28:51.602402128-04:00 level=info message="running checks" addr=https://myserver:8200 environment= version=v0.0.6
```

**Comment by lrstanley** [comment]
I can understand that they may be a little too verbose, however I think the default should be enough to tell that the process is working as intended, without someone having to change the level. When there are no logs, it's hard to tell if the process is hung/stuck on something, or not. IMO, debug level is there for those who know there is a problem, and are trying to reproduce and it's a short lived change.

The above messages are the most important when the you go from "everything is working" to "things aren't unsealing, make sure vault-unseal was running/working" without having to go through another iteration just to enable debugging, etc.

**Comment by reverendj1** [comment]
Understandable. The problem for me is that setting vault-unseal up with systemd and having journald forward to syslog, my logs are just full of vault-unseal notifications and it's difficult to find any useful information for **other** applications. This is not running in a container or a dedicated Vault server. I see you have LOG_QUIET to not send logs to stdout, which would fix this (I have vault-unseal set to log to a separate file, so it can be as verbose as it pleases), however it seems to disable logging altogether. My log file doesn't get anything written to it when I enable it. Am I doing something wrong, or is this a bug?

**Comment by lrstanley** [comment]
Yeah I think log-quiet shouldn't disable file logs if the file log param is enabled.

**Comment by lrstanley** [comment]
Sorry for the delay -- pushed [release v0.0.7](https://github.com/lrstanley/vault-unseal/releases/tag/v0.0.7) which should solve this issue, let me know if you run into any problems.
