### ISSUE TITLE
bug: vault-unseal won't accept read-only config file

### ISSUE THREAD

**Issue by jweisner** [lrstanley/vault-unseal#18]
### 🌧 Describe the problem

A config file set to `0400` results in an error message:

`timestamp=2022-08-23T17:21:33.858258175Z level=fatal message="error reading config" environment= error="permissions of \"/etc/vault-unseal.yaml\" are insecure: r--------, please use 0600" version=0.2.2`

### ⛅ Expected behavior

Config file with `0400` permissions is loaded by the program.

### 🔄 Minimal reproduction

echo '---' > vault-unseal.yaml
chmod 0400 vault-unseal.yaml
vault-unseal -c vault-unseal.yaml

### 💠 Version: vault-unseal

0.2.2

### 🖥 Version: Operating system

linux/alpine

### 🤝 Requirements

- [X] I believe the problem I'm facing is a bug, and is not intended behavior. [Post here if you're not sure](../discussions/new?category=q-a).
- [X] I have confirmed that someone else has not [submitted a similar bug report](../labels/bug).

**Comment by lrstanley** [comment]
[v0.2.3](https://github.com/lrstanley/vault-unseal/releases/tag/v0.2.3) has been released with a fix for this issue.
