### ISSUE TITLE
feature: Make it easy to push config through a shared drive/location

### ISSUE THREAD

**Issue by Enissay** [lrstanley/vault-unseal#25]
### ✨ Describe the feature you'd like

I have 5 nodes which are easy to maintain via a shared drive.
Pushing config for each in `./node${i}/config/vault-unseal.yaml` on the said shared drive.
Sadly they all remain in the shared drive unless I move them away, which makes the whole process pointless.

It would be nice to:
- load the config from folderA => my case the sahred drive
- save it to folderB (working dir) => some location on the host
- optionally delete it from folderA => or it can be done manually as well, what is important is that it doesn't rely on folderA anymore

Unless you might suggest another way todo.

### 🔎 Describe alternatives you've considered

Manually login into each node and apply the needed changes before launching the cluster.

### ⚠ If implemented, do you think this feature will be a breaking change to users?

Not sure

### ⚙ Additional context

It won't affect the others necessarily, it can be made optional.

### 🤝 Requirements

- [X] I have confirmed that someone else has not [submitted a similar feature request](../labels/enhancement).
- [X] If implemented, I believe this feature will help others, in addition to solving my problems.
- [X] I have looked into alternative solutions to the best of my ability.
- [ ] (optional) I would be willing to contribute to testing this feature if implemented, or making a PR to implement this functionality.

**Comment by lrstanley** [comment]
I'm not sure there is value in supporting this in vault-unseal itself -- I don't see others being likely to reuse this kind of logic. This seems like something that should be handled via the method you use to actually deploy vault-unseal itself.
