### ISSUE TITLE
vault-unseal --version output

### ISSUE THREAD

**Issue by ahjohannessen** [lrstanley/vault-unseal#33]
### 🌧 Describe the problem

When I issue this command:

```
vault-unseal --version
```

I get `vault-unseal version: master [latest] (linux, amd64), compiled -`

It used to output a version number as well, like `0.3.0`. I am using this for my ansible-playbook to see if I need to upgrade vault-unseal.

### ⛅ Expected behavior

`vault-unseal version: 0.4.0 [latest] (linux, amd64), compiled -` or at least something that contains the version.

### 🔄 Minimal reproduction

```
vault-unseal --version
```

### 💠 Version: vault-unseal

v0.40.0

### 🖥 Version: Operating system

linux/ubuntu

### 🤝 Requirements

- [X] I believe the problem I'm facing is a bug, and is not intended behavior. [Post here if you're not sure](../discussions/new?category=q-a).
- [X] I have confirmed that someone else has not [submitted a similar bug report](../labels/bug).

**Comment by lrstanley** [comment]
https://github.com/lrstanley/vault-unseal/releases/tag/v0.4.1 should have a fix. sorry about that!

**Comment by ahjohannessen** [comment]
@lrstanley Thanks a lot 👍
