### ISSUE TITLE
Support single Vault node

### ISSUE THREAD

**Issue by Djaler** [lrstanley/vault-unseal#8]
We have a single Vault instance, but validation for `vault_nodes` parameter require us to provide at least 3 urls

**Comment by lrstanley** [comment]
Should be added in with https://github.com/lrstanley/vault-unseal/releases/tag/v0.2.0, though I've hidden the flag by default, as running a single node usually isn't the best idea.

Options:

- `ALLOW_SINGLE_NODE=true`
- `--allow-single-node`
